"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:56:45.279993+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path + "/transactions.csv")
                      .withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))

    merchants_df = (spark.read.option("header", "true")
                   .option("inferSchema", "false")
                   .csv(input_path + "/merchants.csv")
                    .withColumn("ingestion_timestamp", lit(run_date))
                   .withColumn("source_file", lit("merchants.csv"))
                   .withColumn("pipeline_run_id", lit(run_id)))

    # Write the DataFrames to Parquet partitioned by date
    transactions_df.write.mode("overwrite").parquet(output_path + "/bronze/transactions/date=" + run_date)
    merchants_df.write.mode("overwrite").parquet(output_path + "/bronze/merchants/date=" + run_date)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path + "/transactions/date=" + run_date)
                       .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                       .withColumn("amount", col("amount").cast(FloatType())))

    merchants_df = (spark.read.parquet(merchants_path + "/merchants/date=" + run_date)
                   .withColumn("merchant_id", col("merchant_id").cast(StringType())))

    # Cache the small merchants DataFrame
    merchants_df = merchants_df.cache()

    # Filter NULL transaction_id and negative amounts
    filtered_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # Deduplicate on transaction_id keeping the latest ingestion_timestamp
    deduped_df = (filtered_df.withColumn("row_number", 
                                         when(col("transaction_id").isNotNull(), 
                                              (col("ingestion_timestamp").cast("long") - 
                                               col("transaction_date").cast("long") + 1).cast("long")))
                 .withColumn("row_number", 
                              (col("row_number") + col("transaction_id").cast("long").cast("long")).cast("long"))
                  .orderBy(col("transaction_id"), col("row_number").desc())
                 .dropDuplicates(["transaction_id"])
                 .drop("row_number"))

    # Join with merchants (broadcast hint)
    enriched_df = (deduped_df.join(broadcast(merchants_df), deduped_df.col("merchant_id") == merchants_df.col("merchant_id"), "left_outer")
                   .withColumn("quality_flag", 
                               when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))

    # Write the enriched DataFrame to Parquet partitioned by date
    enriched_df.write.mode("overwrite").parquet(output_path + "/silver/transactions/date=" + run_date)

def main(spark, input_path, output_path, run_date, run_id):
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, output_path, run_date, run_id)

    # Transform Silver layer
    transform_silver(spark, output_path + "/bronze/transactions", output_path + "/bronze/merchants", output_path + "/silver", run_date)

    # Write run metadata summary to a JSON file
    run_metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(output_path + "/run_metadata.json", "w") as outfile:
        json.dump(run_metadata, outfile)

if __name__ == "__main__":
    # Initialize SparkSession
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    # Define input and output paths
    input_path = "s3://your-bucket/bronze"
    output_path = "s3://your-bucket/silver"

    # Define run date and run ID
    run_date = "2026-05-27"
    run_id = "run-001"

    # Execute the main function
    main(spark, input_path, output_path, run_date, run_id)


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, avg, collect_set, collect_list, first, last, mode
from pyspark.sql.types import FloatType, StringType, DateType, IntegerType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write Gold layer merchant performance data
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path + "/merchant_performance")

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_spent"),
            count("*").alias("total_txns"),
            avg(col("amount")).alias("avg_txn_value"),
            first("transaction_date").alias("first_txn_date"),
            last("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    # Write Gold layer customer LTV data
    customer_ltv_df.write.mode("overwrite").parquet(output_path + "/customer_ltv")

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(distinct("customer_id")).alias("unique_customers"),
            count(distinct("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write Gold layer daily summary data
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path + "/daily_summary")

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, gold_output_dir, run_date)
    build_customer_ltv(spark, silver_path, gold_output_dir)
    build_daily_summary(spark, silver_path, gold_output_dir, run_date)
    
    # Write run metadata summary
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "status": "success"
    }
    spark.sparkContext.parallelize([run_metadata]).write.mode("overwrite").json(gold_output_dir + "/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
