"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:55:33.620713+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sha2, concat, current_date, current_timestamp, input_file_name, coalesce, row_number
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, DecimalType, TimestampType

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read the input CSV file
    bronze_schema = StructType([
        StructField("transaction_id", StringType()),
        StructField("merchant_id", StringType()),
        StructField("customer_id", StringType()),
        StructField("amount", StringType()),
        StructField("payment_method", StringType()),
        StructField("txn_timestamp", StringType()),
        StructField("merchant_rating", StringType())
    ])
    
    df_bronze = spark.read.csv(input_path, schema=bronze_schema, header=True)
    
    # Add metadata columns
    df_bronze = df_bronze.withColumn("ingestion_timestamp", current_timestamp()) \
                         .withColumn("source_file_name", input_file_name()) \
                        .withColumn("run_date", lit(run_date)) \
                         .withColumn("run_id", lit(run_id))
    
    # Write the DataFrame to Bronze layer partitioned by run_date
    df_bronze.write.mode("overwrite").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read the Bronze layer with partition pruning
    df_bronze = spark.read.parquet(bronze_path).where(col("run_date") == run_date)
    
    # Cast columns to correct types
    df_bronze = df_bronze.withColumn("amount", col("amount").cast(DecimalType(18,2))) \
                         .withColumn("txn_timestamp", col("txn_timestamp").cast(TimestampType())) \
                         .withColumn("merchant_rating", col("merchant_rating").cast(DoubleType()))
    
    # Filter NULL transaction_id and negative amounts
    df_bronze = df_bronze.where(
        (col("transaction_id").isNotNull()) &
        (col("amount") > 0)
    )
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    df_bronze = df_bronze.withColumn("row_num", row_number().over(Window.partitionBy("transaction_id").orderBy(col("txn_timestamp").desc()))) \
                         .filter(col("row_num") == 1) \
                         .drop("row_num")
    
    # Read partner_merchant_mapping and cache it
    df_merchants = spark.read.format("delta").load(merchants_path).cache()
    
    # Join with merchants (broadcast hint)
    df_silver = df_bronze.join(df_merchants, "merchant_id", "inner").broadcast()
    
    # Add quality_flag column
    df_silver = df_silver.withColumn("quality_flag", when((col("duplicate_rate") <= 0.02) & (col("null_merchant_id") <= 0.01), "CLEAN").otherwise("UNMATCHED"))
    
    # Write the DataFrame to Silver layer partitioned by run_date
    df_silver.write.mode("overwrite").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = SparkSession.builder.appName("PartnerFeedPipeline").getOrCreate()
    
    # Define paths and parameters
    input_path = "s3://path/to/bronze/input"
    bronze_path = "s3://path/to/bronze/output"
    merchants_path = "s3://path/to/merchants/mapping"
    output_path = "s3://path/to/silver/output"
    run_date = "2023-10-01"
    run_id = "12345"
    
    # Execute pipeline stages
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sha2, broadcast, coalesce, current_date, current_timestamp, input_file_name, row_number, when
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, DecimalType, TimestampType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    run_metadata = {
        "run_date": run_date,
        "status": "COMPLETED",
        "generated_files": [
            "merchant_performance",
            "customer_ltv",
            "daily_summary"
        ]
    }
    
    spark.sparkContext.parallelize([run_metadata]).toDF().write.mode('overwrite').json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    merchant_performance = (spark.read.format("delta").load(silver_path)
                            .filter(col("status") == "COMPLETED")
                           .groupBy("merchant_id", "merchant_name", "category", "city", "date")
                            .agg(
                                col("total_revenue").alias("total_revenue_completed") if "total_revenue" in [x.name for x in merchant_performance.schema.fields] else sum("amount"),
                                col("txn_count").alias("txn_count") if "txn_count" in [x.name for x in merchant_performance.schema.fields] else count("*"),
                                (count(when(col("status") == "FAILED")) / count("*") * 100).alias("failure_rate_pct") if "status" in [x.name for x in merchant_performance.schema.fields] else 0
                            ))
    
    merchant_performance.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    customer_ltv = (spark.read.format("delta").load(silver_path)
                   .filter(col("status") == "COMPLETED")
                   .groupBy("customer_id")
                   .agg(
                        sum("amount").alias("total_spent"),
                        count("*").alias("total_txns"),
                        approx_count_distinct("payment_method").alias("preferred_payment_method"),
                        min("txn_timestamp").alias("first_txn_date"),
                        max("txn_timestamp").alias("last_txn_date")
                    ))
    
    customer_ltv.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    daily_summary = (spark.read.format("delta").load(silver_path)
                     .filter(col("status") == "COMPLETED")
                    .groupBy("date")
                    .agg(
                         sum("amount").alias("total_revenue"),
                         count("*").alias("total_txns"),
                         countDistinct("customer_id").alias("unique_customers"),
                         countDistinct("merchant_id").alias("unique_merchants"),
                         (count(when(col("status") == "FAILED")) / count("*") * 100).alias("failure_rate_pct")
                     ))
    
    daily_summary.write.partitionBy("date").mode("overwrite").parquet(output_path)
