-- models/marts/mart_merchant_kpis.sql

WITH filtered_transactions AS (
    SELECT
        transaction_id,
        amount,
        status,
        merchant_id,
        customer_id,
        transaction_date,
        payment_method
    FROM {{ ref('fact_transactions') }}
    WHERE status IN ('COMPLETED', 'FAILED')
),

merchant_revenue AS (
    SELECT
        merchant_id,
        SUM(amount) AS total_revenue
    FROM filtered_transactions
    WHERE status = 'COMPLETED'
    GROUP BY merchant_id
),

merchant_transaction_counts AS (
    SELECT
        merchant_id,
        COUNT(*) AS total_transactions,
        COUNT(CASE WHEN status = 'FAILED' THEN 1 END) AS failed_count
    FROM filtered_transactions
    GROUP BY merchant_id
),

merchant_avg_transaction_value AS (
    SELECT
        merchant_id,
        AVG(amount) AS avg_transaction_value
    FROM filtered_transactions
    WHERE status = 'COMPLETED'
    GROUP BY merchant_id
),

merchant_unique_customers AS (
    SELECT
        merchant_id,
        COUNT(DISTINCT customer_id) AS unique_customers
    FROM filtered_transactions
    GROUP BY merchant_id
)

SELECT
    dm.merchant_id,
    dm.merchant_name,
    dm.category,
    dm.city,
    dm.onboarded_date,
    COALESCE(mr.total_revenue, 0) AS total_revenue,
    COALESCE(mtc.total_transactions, 0) AS total_transactions,
    COALESCE(mtc.failed_count, 0) AS failed_count,
    COALESCE((mtc.failed_count::DECIMAL / NULLIF(mtc.total_transactions, 0)) * 100, 0) AS failure_rate_pct,
    COALESCE(ma.avg_transaction_value, 0) AS avg_transaction_value,
    COALESCE(mu.unique_customers, 0) AS unique_customers
FROM {{ ref('dim_merchant') }} dm
LEFT JOIN merchant_revenue mr ON dm.merchant_id = mr.merchant_id
LEFT JOIN merchant_transaction_counts mtc ON dm.merchant_id = mtc.merchant_id
LEFT JOIN merchant_avg_transaction_value ma ON dm.merchant_id = ma.merchant_id
LEFT JOIN merchant_unique_customers mu ON dm.merchant_id = mu.merchant_id
```

```yaml
# models/marts/schema.yml

version: 2

models:
  - name: mart_merchant_kpis
    description: "Aggregated merchant KPIs including total revenue, transaction counts, failure rates, average transaction value, and unique customers."
    columns:
      - name: merchant_id
        description: "Unique identifier for the merchant."
      - name: merchant_name
        description: "Name of the merchant."
      - name: category
        description: "Category of the merchant."
      - name: city
        description: "City where the merchant is located."
      - name: onboarded_date
        description: "Date when the merchant was onboarded."
      - name: total_revenue
        description: "Total revenue generated by the merchant from completed transactions."
      - name: total_transactions
        description: "Total number of transactions for the merchant."
      - name: failed_count
        description: "Number of failed transactions for the merchant."
      - name: failure_rate_pct
        description: "Failure rate percentage for the merchant's transactions."
      - name: avg_transaction_value
        description: "Average transaction value for the merchant's completed transactions."
      - name: unique_customers
        description: "Number of unique customers who made transactions with the merchant."
